GoMovies/GoMovies/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GoMovies.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using Neo4j.Driver;
using Neo4jClient;
using Neo4jClient.Cypher;

namespace GoMovies.Pages
{
    public class IndexModel : PageModel
    {
        private readonly IDriver _driver;

        private readonly ILogger<IndexModel> _logger;
        [BindProperty]
        public Movie Movie { get; set; }
        [BindProperty]
        public Director Director { get; set; }
        [BindProperty]
        public Actor Actor { get; set; }
        public IList<Movie> topMovies { get; set; }
        public IList<Movie> latestMovies { get; set; }

        public IndexModel(ILogger<IndexModel> logger, IDriver driver)
        {
            _logger = logger;
            _driver = driver;
            topMovies = new List<Movie>();
            latestMovies = new List<Movie>();
        }

        public async Task OnGetAsync()
        {
            var list = new List<INode>();
            IAsyncSession session = _driver.AsyncSession();
            try
            {
                var cursor = await session.RunAsync(@"MATCH (m:Movie) RETURN m ORDER BY m.year DESC limit 10");
                list = await cursor.ToListAsync(record =>
                record["m"].As<INode>());
                foreach (var r in list)
                {
                    Movie m = new Movie();
                    m.id = (int)r.Id;
                    m.title = r["title"].As<String>();
                    m.genre = r["genre"].As<String>();
                    m.year = r["year"].As<int>();
                    m.rating = r["rating"].As<double>();
                    m.votes = r["votes"].As<int>();
                    
                    latestMovies.Add(m);
                }

                cursor = await session.RunAsync(@"MATCH (m:Movie) RETURN m ORDER BY m.rating DESC limit 10");
                list = await cursor.ToListAsync(record =>
                record["m"].As<INode>());
                foreach (var r in list)
                {
                    Movie m = new Movie();
                    m.id = (int)r.Id;
                    m.title = r["title"].As<String>();
                    m.genre = r["genre"].As<String>();
                    m.year = r["year"].As<int>();
                    m.rating = r["rating"].As<double>();
                    m.votes = r["votes"].As<int>();

                    topMovies.Add(m);
                }
            }
            finally
            {
                await session.CloseAsync();
            }
        }

        public async Task<IActionResult> OnPostAddMovieAsync()
        {
            if (!this.ModelState.IsValid)
            {
                return this.Page();
            }
            IResultCursor cursor;
            IAsyncSession session = _driver.AsyncSession();
            try
            {
                cursor = await session.RunAsync(@$"MATCH (m:Movie) 
                WHERE m.title='{Movie.title}'AND m.genre='{Movie.genre}' AND m.year='{Movie.year}' 
                RETURN m");
                var node = await cursor.FetchAsync();
                if (node == false)
                {
                    cursor = await session.RunAsync(@$"MATCH (d:Director) WHERE d.name='{Director.name}' RETURN d");
                    var dnode = await cursor.FetchAsync();
                    if (dnode == false)
                        cursor = await session.RunAsync($"CREATE (d:Director {{name:'{Director.name}'}})");

                    cursor = await session.RunAsync(@$"MATCH (a:Actor) WHERE a.name='{Actor.name}' RETURN a");
                    var anode = await cursor.FetchAsync();
                    if (anode == false)
                        cursor = await session.RunAsync($"CREATE (a:Actor {{name:'{Actor.name}'}})");

                    cursor = await session.RunAsync(@$"CREATE (m:Movie {{title: '{Movie.title}', genre: '{Movie.genre}', year: '{Movie.year}', 
                    rating: '0', votes: '0'}})");

                    cursor = await session.RunAsync(@$"MATCH (d:Director) WHERE d.name='{Director.name}'
                    MATCH (a:Actor) WHERE a.name='{Actor.name}'
                    MATCH (m:Movie) WHERE m.title='{Movie.title}' AND m.genre='{Movie.genre}' AND m.year='{Movie.year}'
                    MERGE (a)-[:ACTED_IN]->(m)
                    MERGE (d)-[:DIRECTED]->(m)");
                }                
            }
            finally
            {
                await session.CloseAsync();
            }
            return RedirectToPage("Index");
        }

        public async Task<IActionResult> OnPostAddDirectorAsync()
        {
            if (!this.ModelState.IsValid)
            {
                return this.Page();
            }
            IResultCursor cursor;
            IAsyncSession session = _driver.AsyncSession();
            try
            {
                cursor = await session.RunAsync(@$"MATCH (d:Director) 
                WHERE d.name='{Director.name}'AND d.born='{Director.born}'
                RETURN d");
                var node = await cursor.FetchAsync();
                if (node == false)
                    cursor = await session.RunAsync($"CREATE (d:Director {{name:'{Director.name}', born: '{Director.born}'}})");               
            }
            finally
            {
                await session.CloseAsync();
            }
            return RedirectToPage("Index");
        }

        public async Task<IActionResult> OnPostAddActorAsync()
        {
            if (!this.ModelState.IsValid)
            {
                return this.Page();
            }
            IResultCursor cursor;
            IAsyncSession session = _driver.AsyncSession();
            try
            {
                cursor = await session.RunAsync(@$"MATCH (a:Actor) 
                WHERE a.name='{Actor.name}'AND a.born='{Actor.born}' AND a.birthplace='{Actor.birthplace}'
                RETURN a");
                var node = await cursor.FetchAsync();
                if (node == false)
                    cursor = await session.RunAsync($"CREATE (a:Actor {{name:'{Actor.name}', born: '{Actor.born}', birthplace: '{Actor.birthplace}'}})");
            }
            finally
            {
                await session.CloseAsync();
            }
            return RedirectToPage("Index");
        }
    }
}

GoMovies/GoMovies/Pages/Single.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Neo4j.Driver;
using GoMovies.Models;

namespace GoMovies.Pages
{
    public class SingleModel : PageModel
    {
        private readonly IDriver _driver;
        [BindProperty]
        public int NewRating { get; set; }
        [BindProperty]
        public Movie Movie { get; set; }
        public Director Director { get; set; }
        public Actor Actor { get; set; }
        [BindProperty]
        public Comment Comment { get; set; }
        public IList<Comment> comments { get; set; }
        public SingleModel(IDriver driver)
        {
            _driver = driver;
            Movie = new Movie();
            Director = new Director();
            Actor = new Actor();
            comments = new List<Comment>();
        }

        public async Task<IActionResult> OnGetAsync(int id)
        {
            IResultCursor cursor;
            var list = new List<INode>();
            IAsyncSession session = _driver.AsyncSession();
            try
            {
                cursor = await session.RunAsync($"MATCH (m:Movie) WHERE id(m)={id} RETURN m");
                var node = await cursor.SingleAsync(r => r["m"].As<INode>());

                Movie.id = (int)node.Id;
                Movie.title = node["title"].As<String>();
                Movie.genre = node["genre"].As<String>();
                Movie.year = node["year"].As<int>();
                Movie.rating = node["rating"].As<double>();
                Movie.votes = node["votes"].As<int>();

                cursor = await session.RunAsync($"MATCH (m:Movie)--(d:Director) WHERE id(m)={id} RETURN d");
                node = await cursor.SingleAsync(r => r["d"].As<INode>());
                Director.name = node["name"].As<String>();

                cursor = await session.RunAsync($"MATCH (m:Movie)--(a:Actor) WHERE id(m)={id} RETURN a");
                node = await cursor.SingleAsync(r => r["a"].As<INode>());
                Actor.name = node["name"].As<String>();

                cursor = await session.RunAsync($"MATCH (m:Movie)--(c:Comment) WHERE id(m)={Movie.id} RETURN c");
                list = await cursor.ToListAsync(record =>
                record["c"].As<INode>());
                foreach (var r in list)
                {
                    Comment c = new Comment();
                    c.user = r["user"].As<String>();
                    c.text = r["text"].As<String>();

                    comments.Add(c);
                }
            }
            finally
            {
                await session.CloseAsync();
            }
            return this.Page();
        }

        public async Task<IActionResult> OnPostRateCommentAsync()
        {
            if (!this.ModelState.IsValid)
            {
                return this.Page();
            }
            IResultCursor cursor;
            IAsyncSession session = _driver.AsyncSession();
            try
            {
                cursor = await session.RunAsync($@"MATCH (m:Movie)
                WHERE id(m)={Movie.id}
                RETURN m");
                var node = await cursor.SingleAsync(r => r["m"].As<INode>());

                Movie.id = (int)node.Id;
                Movie.title = node["title"].As<String>();
                Movie.genre = node["genre"].As<String>();
                Movie.year = node["year"].As<int>();
                Movie.rating = node["rating"].As<double>();
                Movie.votes = node["votes"].As<int>();

                double temp = Movie.rating * Movie.votes;
                temp += NewRating;
                Movie.rating = temp / (++Movie.votes);

                cursor = await session.RunAsync(@$"CREATE (c:Comment {{user: '{Comment.user}', text: '{Comment.text}'}}) RETURN c");
                node = await cursor.SingleAsync(r => r["c"].As<INode>());
                int cid = (int)node.Id;

                cursor = await session.RunAsync($@"MATCH (c:Comment) WHERE id(c)={cid}
                MATCH (m:Movie) WHERE id(m)={Movie.id} SET m.rating = '{Movie.rating}' SET m.votes = '{Movie.votes}'
                MERGE (c)-[:COMMENTED_ON]->(m)");
            }
            finally
            {
                await session.CloseAsync();
            }
            return Redirect("Single?id=" + Movie.id);
        }

        public async Task<IActionResult> OnPostDeleteMovieAsync()
        {
            if (!this.ModelState.IsValid)
            {
                return this.Page();
            }
            IResultCursor cursor;
            IAsyncSession session = _driver.AsyncSession();
            try
            {
                cursor = await session.RunAsync($@"MATCH (m:Movie)--(c:Comment)
                WHERE id(m)={Movie.id}
                DETACH DELETE c
                DETACH DELETE m");
            }
            finally
            {
                await session.CloseAsync();
            }
            return RedirectToPage("Index");
        }
    }
}

GoMovies/GoMovies/Pages/Single.cshtml
@page
@model GoMovies.Pages.SingleModel
@{
    ViewData["Title"] = "Single";
}

<!DOCTYPE html>
<html>
<head>
    <!-- for-mobile-apps -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <script type="application/x-javascript">
        addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false);
               function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!-- //for-mobile-apps -->
    <link href="css/bootstrap.css" rel="stylesheet" type="text/css" media="all" />
    <!-- pop-up -->
    <link href="css/popuo-box.css" rel="stylesheet" type="text/css" media="all" />
    <!-- //pop-up -->
    <link href="css/easy-responsive-tabs.css" rel='stylesheet' type='text/css' />
    <link rel="stylesheet" type="text/css" href="css/zoomslider.css" />
    <link rel="stylesheet" type="text/css" href="css/style.css" />
    <link href="css/font-awesome.css" rel="stylesheet">
    <script type="text/javascript" src="js/modernizr-2.6.2.min.js"></script>
    <!--/web-fonts-->
    <link href='//fonts.googleapis.com/css?family=Tangerine:400,700' rel='stylesheet' type='text/css'>
    <link href="//fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900" rel="stylesheet">
    <link href='//fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
    <!--//web-fonts-->
</head>
<body>
    <!--/main-header-->
    <!--/banner-section-->
    <div id="demo-1" class="banner-inner">
        <div class="banner-inner-dott">
            <div class="header-w3-agileits" id="home">
                <div class="inner-header-agile part2">
                    <nav class="navbar navbar-default">
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                            <h1><a asp-page="Index"><span>G</span>o<span>M</span>ovies</a></h1>
                        </div>
                        <!-- navbar-header -->
                        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                            <ul class="nav navbar-nav">
                                <li class="active"><a asp-page="Index">Home</a></li>
                            </ul>
                        </div>
                        <div class="clearfix"> </div>
                    </nav>
                </div>

            </div>
        </div>
    </div>

    <div class="w3_content_agilleinfo_inner">
        <div class="agile_featured_movies">
            <div class="inner-agile-w3l-part-head">
                <h3 class="w3l-inner-h-title">@Model.Movie.title</h3>
            </div>
            <div class="latest-news-agile-info">
                <div class="col-md-8 latest-news-agile-left-content">
                    <div class="single video_agile_player">

                        <div class="video-grid-single-page-agileits">
                            <div data-video="f2Z65fobH2I" id="video"> <img src="images/@(Model.Movie.title)_Single.jpg" alt="" class="img-responsive" /> </div>
                        </div>
                        <h4>@Model.Movie.title | @Model.Movie.genre | @Model.Movie.year | @Model.Actor.name | @Model.Director.name</h4>
                    </div>
                    <div class="clearfix"> </div>
                    <div>
                        <p>Rating: <b>@Model.Movie.rating.ToString("0.00")</b>/5 (<b>@Model.Movie.votes</b> votes)</p>
                    </div>
                    <div class="clearfix"> </div>
                    <div class="deletebutton">
                        <form method="post">
                            <button type="submit" class="btn btn-danger" asp-page-handler="DeleteMovie">Delete</button>
                            <input type="hidden" asp-for="Movie.id" class="form-control" />
                        </form>
                    </div>
                    <div class="clearfix"> </div>
                    <div class="response">
                        <h4>Comments</h4>
                        @foreach (var c in Model.comments)
                        {
                            <div class="media response-info">
                                <div class="media-left response-text-left">
                                    <h5>@c.user</h5>
                                </div>
                                <div class="media-body response-text-right">
                                    <p>
                                        @c.text
                                    </p>
                                </div>
                                <div class="clearfix"> </div>
                            </div>
                        }
                    </div>
                    <div class="all-comments-info">
                        <h5>RATE AND COMMENT</h5>
                        <div class="agile-info-wthree-box">
                            <form method="post">
                                <div class="col-md-6 form-info">
                                    <input asp-for="Comment.user" type="text" placeholder="Your Name" required="">
                                    <select asp-for="NewRating">
                                        <option value="" disabled selected>Select your option</option>
                                        <option value="1">1</option>
                                        <option value="2">2</option>
                                        <option value="3">3</option>
                                        <option value="4">4</option>
                                        <option value="5">5</option>
                                    </select>
                                </div>
                                <div class="col-md-6 form-info">
                                    <textarea asp-for="Comment.text" placeholder="Message" required=""></textarea>
                                    <input type="submit" asp-page-handler="RateComment" value="SEND">
                                    <input type="hidden" asp-for="Movie.id" class="form-control" />
                                </div>
                                <div class="clearfix"> </div>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>

    <div class="contact-w3ls" id="contact">
        <div class="footer-w3lagile-inner">
        </div>
    </div>

    <div class="w3agile_footer_copy">
        <p>© 2021 GoMovies. All rights reserved | Design by Miloš Veljanovski</p>
    </div>
    <a href="#home" id="toTop" class="scroll" style="display: block;"> <span id="toTopHover" style="opacity: 1;"> </span></a>

    <script src="js/jquery-1.11.1.min.js"></script>
    <!-- Dropdown-Menu-JavaScript -->
    <script>
    $(document).ready(function () {
            $(".dropdown").hover(
                function () {
                    $('.dropdown-menu', this).stop(true, true).slideDown("fast");
                    $(this).toggleClass('open');
                },
                function () {
                    $('.dropdown-menu', this).stop(true, true).slideUp("fast");
                    $(this).toggleClass('open');
                }
            );
        });</script>
    <!-- //Dropdown-Menu-JavaScript -->
    <!-- search-jQuery -->
    <script src="js/main.js"></script>

    <script src="js/simplePlayer.js"></script>
    <script>
    $("document").ready(function () {
            $("#video").simplePlayer();
        });</script>
    <script>
    $("document").ready(function () {
            $("#video1").simplePlayer();
        });</script>
    <script>
    $("document").ready(function () {
            $("#video2").simplePlayer();
        });</script>
    <script>
    $("document").ready(function () {
            $("#video3").simplePlayer();
        });</script>
    <script>
    $("document").ready(function () {
            $("#video4").simplePlayer();
        });</script>
    <script>
    $("document").ready(function () {
            $("#video5").simplePlayer();
        });</script>
    <script>
    $("document").ready(function () {
            $("#video6").simplePlayer();
        });</script>
    <script>
    $("document").ready(function () {
            $("#video6").simplePlayer();
        });</script>

    <!-- pop-up-box -->
    <script src="js/jquery.magnific-popup.js" type="text/javascript"></script>
    <!--//pop-up-box -->

    <div id="small-dialog1" class="mfp-hide">
        <iframe src="https://player.vimeo.com/video/165197924?color=ffffff&title=0&byline=0&portrait=0"></iframe>
    </div>
    <div id="small-dialog2" class="mfp-hide">
        <iframe src="https://player.vimeo.com/video/165197924?color=ffffff&title=0&byline=0&portrait=0"></iframe>
    </div>
    <script>
    $(document).ready(function () {
            $('.w3_play_icon,.w3_play_icon1,.w3_play_icon2').magnificPopup({
                type: 'inline',
                fixedContentPos: false,
                fixedBgPos: true,
                overflowY: 'auto',
                closeBtnInside: true,
                preloader: false,
                midClick: true,
                removalDelay: 300,
                mainClass: 'my-mfp-zoom-in'
            });

        });</script>
    <script src="js/easy-responsive-tabs.js"></script>
    <script>
    $(document).ready(function () {
            $('#horizontalTab').easyResponsiveTabs({
                type: 'default', //Types: default, vertical, accordion
                width: 'auto', //auto or any width like 600px
                fit: true,   // 100% fit in a container
                closed: 'accordion', // Start closed if in accordion view
                activate: function (event) { // Callback function if tab is switched
                    var $tab = $(this);
                    var $info = $('#tabInfo');
                    var $name = $('span', $info);
                    $name.text($tab.text());
                    $info.show();
                }
            });
            $('#verticalTab').easyResponsiveTabs({
                type: 'vertical',
                width: 'auto',
                fit: true
            });
        });</script>
    <link href="css/owl.carousel.css" rel="stylesheet" type="text/css" media="all">
    <script src="js/owl.carousel.js"></script>
    <script>
    $(document).ready(function () {
            $("#owl-demo").owlCarousel({

                autoPlay: 3000, //Set AutoPlay to 3 seconds
                autoPlay: true,
                navigation: true,

                items: 5,
                itemsDesktop: [640, 4],
                itemsDesktopSmall: [414, 3]

            });

        });</script>

    <!--/script-->
    <script type="text/javascript" src="js/move-top.js"></script>
    <script type="text/javascript" src="js/easing.js"></script>

    <script type="text/javascript">
    jQuery(document).ready(function ($) {
            $(".scroll").click(function (event) {
                event.preventDefault();
                $('html,body').animate({ scrollTop: $(this.hash).offset().top }, 900);
            });
        });</script>
    <script type="text/javascript">
    $(document).ready(function () {
            /*
            var defaults = {
                    containerID: 'toTop', // fading element id
                containerHoverID: 'toTopHover', // fading element hover id
                scrollSpeed: 1200,
                easingType: 'linear'
                };
            */

            $().UItoTop({ easingType: 'easeOutQuart' });

        });</script>
    <!--end-smooth-scrolling-->
    <script src="js/bootstrap.js"></script>



</body>
</html>